name: code-style
on:
  - push
  - pull_request
jobs:
  saga:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm install -g nx
      - run: npm ci
      - run: nx run saga:lint --verbose
  demo-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm install -g nx
      - run: npm ci
      - run: nx run demo-app:lint --verbose
  chrome-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm install -g nx
      - run: npm ci
      - run: nx run chrome-extension:lint --verbose
