name: release
on:
  push:
    branches:
      - master
jobs:
  saga:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm install -g nx
      - run: nx affected:libs | grep saga
      - run: npm ci
      - run: nx run saga:lint --verbose
      - run: nx run saga:test --verbose --code-coverage
      - uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ./coverage/packages/saga/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nx run saga:build --verbose
      - run: nx run saga:readme
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
